spring:
  application:
    name: blanche-bridal

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ransilu.deelaka@gmail.com
    password: olzr sxgr gqkz swxv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

jwt:
  expiration: 86400000

app:
  frontend-url: http://localhost:3000